# Generated by Django 3.1 on 2020-09-25 09:26

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Başlık')),
                ('summary', models.CharField(max_length=90, verbose_name='Açıklama')),
                ('contentTitle', models.TextField(max_length=400, verbose_name='Başlık Içeriği')),
                ('articleImage', models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotograf Ekle')),
                ('content', ckeditor.fields.RichTextField()),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
        ),
    ]
