# Generated by Django 3.1 on 2020-09-25 15:32

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
