# Generated by Django 3.1 on 2020-09-25 15:50

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_auto_20200925_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Başlık')),
                ('summary', models.CharField(max_length=90, verbose_name='Açıklama')),
                ('contentTitle', models.TextField(max_length=400, verbose_name='Başlık Içeriği')),
                ('articleImage', models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotograf Ekle')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Başlık')),
                ('summary', models.CharField(max_length=90, verbose_name='Açıklama')),
                ('contentTitle', models.TextField(max_length=400, verbose_name='Başlık Içeriği')),
                ('articleImage', models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotograf Ekle')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Başlık')),
                ('summary', models.CharField(max_length=90, verbose_name='Açıklama')),
                ('contentTitle', models.TextField(max_length=400, verbose_name='Başlık Içeriği')),
                ('articleImage', models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotograf Ekle')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
        ),
        migrations.CreateModel(
            name='Forensic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Başlık')),
                ('summary', models.CharField(max_length=90, verbose_name='Açıklama')),
                ('contentTitle', models.TextField(max_length=400, verbose_name='Başlık Içeriği')),
                ('articleImage', models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotograf Ekle')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
        ),
    ]
