# Generated by Django 3.1 on 2020-09-28 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200926_2116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Translate',
        ),
    ]
