# Generated by Django 3.1 on 2020-10-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_translate'),
    ]

    operations = [
        migrations.AddField(
            model_name='forensic',
            name='articlesVideo',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
        migrations.AddField(
            model_name='network',
            name='articlesVideo',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
        migrations.AddField(
            model_name='security',
            name='articlesVideo',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
        migrations.AddField(
            model_name='tools',
            name='articlesVideo',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
        migrations.AddField(
            model_name='translate',
            name='articlesVideo',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
