# Generated by Django 3.1 on 2020-10-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20201002_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forensic',
            name='articleImage',
            field=models.FileField(blank=True, null=True, upload_to='images', verbose_name='Fotograf Ekle'),
        ),
        migrations.AlterField(
            model_name='network',
            name='articleImage',
            field=models.FileField(blank=True, null=True, upload_to='images', verbose_name='Fotograf Ekle'),
        ),
        migrations.AlterField(
            model_name='security',
            name='articleImage',
            field=models.FileField(blank=True, null=True, upload_to='images', verbose_name='Fotograf Ekle'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='articleImage',
            field=models.FileField(blank=True, null=True, upload_to='images', verbose_name='Fotograf Ekle'),
        ),
        migrations.AlterField(
            model_name='translate',
            name='articleImage',
            field=models.FileField(blank=True, null=True, upload_to='images', verbose_name='Fotograf Ekle'),
        ),
    ]
