# Generated by Django 3.1 on 2021-01-24 10:20

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0010_auto_20201002_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='karisik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Başlık')),
                ('summary', models.CharField(max_length=90, unique=True, verbose_name='Açıklama')),
                ('articleImage', models.FileField(blank=True, null=True, upload_to='images', verbose_name='Fotograf Ekle')),
                ('contentEn', ckeditor_uploader.fields.RichTextUploadingField()),
                ('contentTr', ckeditor_uploader.fields.RichTextUploadingField()),
                ('articlesVideo', models.FileField(blank=True, null=True, upload_to='videos')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
            options={
                'ordering': ['-createDate'],
            },
        ),
        migrations.CreateModel(
            name='SoC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True, verbose_name='Başlık')),
                ('summary', models.CharField(max_length=90, verbose_name='Açıklama')),
                ('articleImage', models.FileField(blank=True, null=True, upload_to='images', verbose_name='Fotograf Ekle')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('articlesVideo', models.FileField(blank=True, null=True, upload_to='videos')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
            options={
                'ordering': ['-createDate'],
            },
        ),
        migrations.RemoveField(
            model_name='tools',
            name='author',
        ),
        migrations.RemoveField(
            model_name='translate',
            name='author',
        ),
        migrations.RemoveField(
            model_name='forensic',
            name='contentTitle',
        ),
        migrations.RemoveField(
            model_name='network',
            name='contentTitle',
        ),
        migrations.DeleteModel(
            name='Security',
        ),
        migrations.DeleteModel(
            name='Tools',
        ),
        migrations.DeleteModel(
            name='Translate',
        ),
    ]
