# Generated by Django 3.1 on 2021-01-24 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20210124_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='karisik',
            old_name='contentEn',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='karisik',
            name='contentTr',
        ),
    ]
